### ISSUE TITLE
[BUG] Value for Chris Diamantopoulos is wrong

### ISSUE THREAD

**Issue by BiggerJ** [AhoyLemon/kinda.fun-old#110]
## The Game

Comparatively Famous

## The Bug

The value given for Chris Diamantopoulos is $299 - it is currently $399.

## To Reproduce

Play the game until Chris Diamantopoulos appears - or just check the game's data.

## Screenshots!

![cf](https://user-images.githubusercontent.com/27851273/111894989-86060600-8a5f-11eb-9a7e-d5c3417d2102.png)
![cameo](https://user-images.githubusercontent.com/27851273/111895000-8dc5aa80-8a5f-11eb-96d0-ed007257fbb6.png)

**Comment by AhoyLemon** [comment]
Thanks for the report.

So, rather than doing live polling, which would be problematic, kinda.fun gets a one-time snapshot of all celebrity values, at the time that they're added to the database.

As such, it's *totally* 100% gonna happen that at times, the game's value disagrees with the live Cameo value, because some people are adjusting their prices a bunch, depending on whatever factors. I could choose to chase that dragon, instead I've chosen to just accept it.

As it happens, Chris has actually dropped his value right now.

![image](https://user-images.githubusercontent.com/3413200/112371487-a8d92a00-8cac-11eb-9c89-2bee732bbaa8.png)
